export default class WorkProvider {
  static getWorks() {
    return [
      {
        id: "0",
        title: "Reforma de restaurante",
        description:
          "Reforma integral de restaurante en Alonso Martinez.",
        year: 2020,
        images: [
          {
            original: "https://i.ibb.co/s9WtwgV/rest-post-01.jpg",
            medium: "https://i.ibb.co/s9WtwgV/rest-post-01.jpg",
            thumbnail: "https://i.ibb.co/RTj70gD/rest-post-01.jpg",
            originalAlt: "Entrada",
            thumbnailAlt: "Entrada",
          },
          {
            original: "https://i.ibb.co/xSbs5GB/rest-post-02.jpg",
            medium: "https://i.ibb.co/xSbs5GB/rest-post-02.jpg",
            thumbnail: "https://i.ibb.co/HDy2gYb/rest-post-02.jpg",
            originalAlt: "Barra",
            thumbnailAlt: "Barra",
          },
          {
            original: "https://i.ibb.co/Y8XFqYd/rest-post-03.jpg",
            medium: "https://i.ibb.co/Y8XFqYd/rest-post-03.jpg",
            thumbnail: "https://i.ibb.co/bLFM8qv/rest-post-03.jpg",
            originalAlt: "Restaurante 1",
            thumbnailAlt: "Restaurante 1",
          },
          {
            original: "https://i.ibb.co/gwkBRz1/rest-post-04.jpg",
            medium: "https://i.ibb.co/gwkBRz1/rest-post-04.jpg",
            thumbnail: "https://i.ibb.co/wC5xzMH/rest-post-04.jpg",
            originalAlt: "Vinilo",
            thumbnailAlt: "Vinilo",
          },
          {
            original: "https://i.ibb.co/hLhkrJx/rest-post-05.jpg",
            medium: "https://i.ibb.co/hLhkrJx/rest-post-05.jpg",
            thumbnail: "https://i.ibb.co/xXPywtK/rest-post-05.jpg",
            originalAlt: "Baño 1",
            thumbnailAlt: "Baño 1",
          },
          {
            original: "https://i.ibb.co/68XxZ8D/rest-post-06.jpg",
            medium: "https://i.ibb.co/68XxZ8D/rest-post-06.jpg",
            thumbnail: "https://i.ibb.co/KDKkGDV/rest-post-06.jpg",
            originalAlt: "Restaurante 2",
            thumbnailAlt: "Restaurante 2",
          },
          {
            original: "https://i.ibb.co/xFTcLCZ/rest-post-07.jpg",
            medium: "https://i.ibb.co/xFTcLCZ/rest-post-07.jpg",
            thumbnail: "https://i.ibb.co/2Z4LhnJ/rest-post-07.jpg",
            originalAlt: "Baño 2",
            thumbnailAlt: "Baño 2",
          },
          {
            original: "https://i.ibb.co/jTtzhrb/rest-post-08.jpg",
            medium: "https://i.ibb.co/jTtzhrb/rest-post-08.jpg",
            thumbnail: "https://i.ibb.co/Qf0k9Kp/rest-post-08.jpg",
            originalAlt: "Barra 2",
            thumbnailAlt: "Barra 2",
          },
          {
            original: "https://i.ibb.co/44Nh8mP/rest-post-09.jpg",
            medium: "https://i.ibb.co/44Nh8mP/rest-post-09.jpg",
            thumbnail: "https://i.ibb.co/c2T46gD/rest-post-09.jpg",
            originalAlt: "Restaurante 3",
            thumbnailAlt: "Restaurante 3",
          },
          {
            original: "https://i.ibb.co/2KDsmyf/rest-post-10.jpg",
            medium: "https://i.ibb.co/2KDsmyf/rest-post-10.jpg",
            thumbnail: "https://i.ibb.co/zfy7jr0/rest-post-10.jpg",
            originalAlt: "Restaurante 4",
            thumbnailAlt: "Restaurante 4",
          },
        ],
      },
      {
        id: "1",
        title: "Reforma de estancia en chalet unifamiliar",
        description:
          "Reforma de estancia en chalet, barra americana, cambio de puerta corredera por puertas. Decoracion por @camomila.atelier",
        year: 2016,
        images: [
          {
            original: "https://i.ibb.co/0qHQ3XN/nun1-post-01.jpg",
            medium: "https://i.ibb.co/Nxc7z3h/nun1-post-01.jpg",
            thumbnail: "https://i.ibb.co/xhx3Qsv/nun1-post-01.jpg",
            originalAlt: "Cocina iluminada",
            thumbnailAlt: "Cocina iluminada",
          },
          {
            original: "https://i.ibb.co/zmkRZCp/nun1-post-02.jpg",
            medium: "https://i.ibb.co/j8pMDqm/nun1-post-02.jpg",
            thumbnail: "https://i.ibb.co/p1mzdNc/nun1-post-02.jpg",
            originalAlt: "Cocina poco iluminada",
            thumbnailAlt: "Cocina poco iluminada",
          },
          {
            original: "https://i.ibb.co/BywM7dW/nun1-post-03.jpg",
            medium: "https://i.ibb.co/9bG5fzK/nun1-post-03.jpg",
            thumbnail: "https://i.ibb.co/fkQwKB6/nun1-post-03.jpg",
            originalAlt: "Cocina lateral",
            thumbnailAlt: "Cocina lateral",
          },
          {
            original: "https://i.ibb.co/gFQbR75/nun1-post-04.jpg",
            medium: "https://i.ibb.co/TqJDgTV/nun1-post-04.jpg",
            thumbnail: "https://i.ibb.co/4gCwVf6/nun1-post-04.jpg",
            originalAlt: "Barra americana",
            thumbnailAlt: "Barra americana",
          },
        ],
      },
      {
        id: "2",
        title: "Reforma integral de vivienda en altura",
        description:
          "Reducción del número de habitaciones de 3 habitaciones a 2 habitaciones, dormitorio principal más habitación de invitados. Cocina americana con barra, ampliación de ventanas, eliminación del gotelé. Decoración por @camomila.atelier",
        year: 2017,
        images: [
          {
            original: "https://i.ibb.co/YZKZy3H/nun2-post-01.jpg",
            medium: "https://i.ibb.co/jRxRWTn/nun2-post-01.jpg",
            thumbnail: "https://i.ibb.co/nCVCnbx/nun2-post-01.jpg",
            originalAlt: "Salon lateral",
            thumbnailAlt: "Salon lateral",
          },
          {
            original: "https://i.ibb.co/zGqDC8q/nun2-post-02.jpg",
            medium: "https://i.ibb.co/r4DNqbD/nun2-post-02.jpg",
            thumbnail: "https://i.ibb.co/ZWq7vHq/nun2-post-02.jpg",
            originalAlt: "Salon atras",
            thumbnailAlt: "Salon atras",
          },
          {
            original: "https://i.ibb.co/19rRQBW/nun2-post-03.jpg",
            medium: "https://i.ibb.co/kh4qBzC/nun2-post-03.jpg",
            thumbnail: "https://i.ibb.co/MRcPSK0/nun2-post-03.jpg",
            originalAlt: "Cocina",
            thumbnailAlt: "Cocina",
          },
          {
            original: "https://i.ibb.co/Rp3PDLv/nun2-post-04.jpg",
            medium: "https://i.ibb.co/bgsLKpW/nun2-post-04.jpg",
            thumbnail: "https://i.ibb.co/rGxMwn7/nun2-post-04.jpg",
            originalAlt: "Dormitorio principal",
            thumbnailAlt: "Dormitorio principal",
          },
          {
            original: "https://i.ibb.co/Q81GDcr/nun2-post-05.jpg",
            medium: "https://i.ibb.co/dbzymcG/nun2-post-05.jpg",
            thumbnail: "https://i.ibb.co/rb1Jdt4/nun2-post-05.jpg",
            originalAlt: "Dormitorio secundario",
            thumbnailAlt: "Dormitorio secundario",
          },
          {
            original: "https://i.ibb.co/QvvwVj8/nun2-post-06.jpg",
            medium: "https://i.ibb.co/v44nWvs/nun2-post-06.jpg",
            thumbnail: "https://i.ibb.co/5hhH3xY/nun2-post-06.jpg",
            originalAlt: "Baño principal",
            thumbnailAlt: "Baño principal",
          },
          {
            original: "https://i.ibb.co/Jt5Nr4z/nun2-post-07.jpg",
            medium: "https://i.ibb.co/NCZXWPL/nun2-post-07.jpg",
            thumbnail: "https://i.ibb.co/jfgd32L/nun2-post-07.jpg",
            originalAlt: "Baño secundario",
            thumbnailAlt: "Baño secundario",
          },
        ],
      },
      {
        id: "3",
        title: "Reforma integral de sastreria",
        description:
          "Cambio de suelo, paredes, escaparates, baños, probadores...",
        year: 2019,
        images: [
          {
            original: "https://i.ibb.co/Ldh88qr/hl-wh-01.jpg",
            medium: "https://i.ibb.co/Ldh88qr/hl-wh-01.jpg",
            thumbnail: "https://i.ibb.co/JjFKKbq/hl-wh-01.jpg",
            originalAlt: "Obra estancia principal",
            thumbnailAlt: "Obra estancia principal",
          },
          {
            original: "https://i.ibb.co/RgnHtB2/hl-wh-02.jpg",
            medium: "https://i.ibb.co/RgnHtB2/hl-wh-02.jpg",
            thumbnail: "https://i.ibb.co/9pXYBVn/hl-wh-02.jpg",
            originalAlt: "Obra probadores",
            thumbnailAlt: "Obra probadores",
          },
          {
            original: "https://i.ibb.co/fkY9dTs/hl-wh-03.jpg",
            medium: "https://i.ibb.co/fkY9dTs/hl-wh-03.jpg",
            thumbnail: "https://i.ibb.co/wSN7h2f/hl-wh-03.jpg",
            originalAlt: "Obra estancia principal",
            thumbnailAlt: "Obra estancia principal",
          },
          {
            original: "https://i.ibb.co/FWgNSyg/hl-post-01.jpg",
            medium: "https://i.ibb.co/FWgNSyg/hl-post-01.jpg",
            thumbnail: "https://i.ibb.co/1n8hDP8/hl-post-01.jpg",
            originalAlt: "Estancia principal",
            thumbnailAlt: "Estancia principal",
          },
          {
            original: "https://i.ibb.co/NFR6t8D/hl-post-02.jpg",
            medium: "https://i.ibb.co/NFR6t8D/hl-post-02.jpg",
            thumbnail: "https://i.ibb.co/3TKy4D6/hl-post-02.jpg",
            originalAlt: "Estancia principal lateral",
            thumbnailAlt: "Estancia principal lateral",
          },
          {
            original: "https://i.ibb.co/5x408p8/hl-post-03.jpg",
            medium: "https://i.ibb.co/5x408p8/hl-post-03.jpg",
            thumbnail: "https://i.ibb.co/yBP9yvy/hl-post-03.jpg",
            originalAlt: "Estancia secundaria",
            thumbnailAlt: "Estancia secundaria",
          },
          {
            original: "https://i.ibb.co/rxj1TrC/hl-post-04.jpg",
            medium: "https://i.ibb.co/rxj1TrC/hl-post-04.jpg",
            thumbnail: "https://i.ibb.co/R3FVZwx/hl-post-04.jpg",
            originalAlt: "Baño",
            thumbnailAlt: "Baño",
          },
          {
            original: "https://i.ibb.co/fYcfTm3/hl-post-05.jpg",
            medium: "https://i.ibb.co/fYcfTm3/hl-post-05.jpg",
            thumbnail: "https://i.ibb.co/3yJ2Ptx/hl-post-05.jpg",
            originalAlt: "Probadores",
            thumbnailAlt: "Probadores",
          },
        ],
      },
      {
        id: "4",
        title: "Reforma integral de vivienda en altura",
        description:
          "Reforma integral de vivienda en altura en Madrid centro. Cambio de suelos, reforma de baño, reforma de cocina",
        year: 2018,
        images: [
          {
            original: "https://i.ibb.co/gdQmnTX/pe-post-01.jpg",
            medium: "https://i.ibb.co/gdQmnTX/pe-post-01.jpg",
            thumbnail: "https://i.ibb.co/FXcmPwf/pe-post-01.jpg",
            originalAlt: "Salon",
            thumbnailAlt: "Salon",
          },
          {
            original: "https://i.ibb.co/DQ5mg8b/pe-post-02.jpg",
            medium: "https://i.ibb.co/DQ5mg8b/pe-post-02.jpg",
            thumbnail: "https://i.ibb.co/TtmJqbT/pe-post-02.jpg",
            originalAlt: "Comedor",
            thumbnailAlt: "Comedor",
          },
          {
            original: "https://i.ibb.co/1J5Btkj/pe-post-03.jpg",
            medium: "https://i.ibb.co/1J5Btkj/pe-post-03.jpg",
            thumbnail: "https://i.ibb.co/NnPfdMb/pe-post-03.jpg",
            originalAlt: "Entrada",
            thumbnailAlt: "Entrada",
          },
          {
            original: "https://i.ibb.co/p1JN4Ys/pe-post-04.jpg",
            medium: "https://i.ibb.co/p1JN4Ys/pe-post-04.jpg",
            thumbnail: "https://i.ibb.co/tH8nYVN/pe-post-04.jpg",
            originalAlt: "Dormitorio principal",
            thumbnailAlt: "Dormitorio principal",
          },
          {
            original: "https://i.ibb.co/JrnTjnH/pe-post-05.jpg",
            medium: "https://i.ibb.co/JrnTjnH/pe-post-05.jpg",
            thumbnail: "https://i.ibb.co/qmB8YBp/pe-post-05.jpg",
            originalAlt: "Salon lateral",
            thumbnailAlt: "Salon lateral",
          },
          {
            original: "https://i.ibb.co/gyv2mSR/pe-post-06.jpg",
            medium: "https://i.ibb.co/gyv2mSR/pe-post-06.jpg",
            thumbnail: "https://i.ibb.co/wyJkBSz/pe-post-06.jpg",
            originalAlt: "Baño principal",
            thumbnailAlt: "Baño principal",
          },
        ],
      },
      {
        id: "5",
        title: "Reforma integral de tienda",
        description: "",
        year: 2000,
        images: [
          {
            original: "https://i.ibb.co/xGVq6Rt/hann0-post-01.jpg",
            medium: "https://i.ibb.co/xGVq6Rt/hann0-post-01.jpg",
            thumbnail: "https://i.ibb.co/rMn2H1R/hann0-post-01.jpg",
            originalAlt: "Entrada",
            thumbnailAlt: "Entrada",
          },
          {
            original: "https://i.ibb.co/g6dBVjC/hann0-post-02.jpg",
            medium: "https://i.ibb.co/g6dBVjC/hann0-post-02.jpg",
            thumbnail: "https://i.ibb.co/yVpbSfJ/hann0-post-02.jpg",
            originalAlt: "Vestidor 1",
            thumbnailAlt: "Vestidor 1",
          },
          {
            original: "https://i.ibb.co/fHLd9Jk/hann0-post-03.jpg",
            medium: "https://i.ibb.co/fHLd9Jk/hann0-post-03.jpg",
            thumbnail: "https://i.ibb.co/QMtvk0P/hann0-post-03.jpg",
            originalAlt: "Vestidor 2",
            thumbnailAlt: "Vestidor 2",
          },
          {
            original: "https://i.ibb.co/B4gnzpN/hann0-post-04.jpg",
            medium: "https://i.ibb.co/B4gnzpN/hann0-post-04.jpg",
            thumbnail: "https://i.ibb.co/VHvwj1m/hann0-post-04.jpg",
            originalAlt: "Vestidor 3",
            thumbnailAlt: "Vestidor 3",
          },
          {
            original: "https://i.ibb.co/18dDvBv/hann0-post-05.jpg",
            medium: "https://i.ibb.co/18dDvBv/hann0-post-05.jpg",
            thumbnail: "https://i.ibb.co/HnxWFRF/hann0-post-05.jpg",
            originalAlt: "Escaparate 1",
            thumbnailAlt: "Escaparate 1",
          },
          {
            original: "https://i.ibb.co/1RQFHVx/hann0-post-06.jpg",
            medium: "https://i.ibb.co/1RQFHVx/hann0-post-06.jpg",
            thumbnail: "https://i.ibb.co/dkM8n9y/hann0-post-06.jpg",
            originalAlt: "Mesa",
            thumbnailAlt: "Mesa",
          },
          {
            original: "https://i.ibb.co/RSg1BQ4/hann0-post-07.jpg",
            medium: "https://i.ibb.co/RSg1BQ4/hann0-post-07.jpg",
            thumbnail: "https://i.ibb.co/qnDzWmF/hann0-post-07.jpg",
            originalAlt: "Vestidor 4",
            thumbnailAlt: "Vestidor 4",
          },
          {
            original: "https://i.ibb.co/yQTP58b/hann0-post-08.jpg",
            medium: "https://i.ibb.co/yQTP58b/hann0-post-08.jpg",
            thumbnail: "https://i.ibb.co/W295FcY/hann0-post-08.jpg",
            originalAlt: "Escaparate 2",
            thumbnailAlt: "Escaparate 2",
          },
          {
            original: "https://i.ibb.co/QjS7jXH/hann0-post-09.jpg",
            medium: "https://i.ibb.co/QjS7jXH/hann0-post-09.jpg",
            thumbnail: "https://i.ibb.co/FqZkqnY/hann0-post-09.jpg",
            originalAlt: "Vestidor 5",
            thumbnailAlt: "Vestidor 5",
          },
          {
            original: "https://i.ibb.co/vPHBwZS/hann0-post-10.jpg",
            medium: "https://i.ibb.co/vPHBwZS/hann0-post-10.jpg",
            thumbnail: "https://i.ibb.co/J7KdB59/hann0-post-10.jpg",
            originalAlt: "Vestidor 6",
            thumbnailAlt: "Vestidor 6",
          },
        ],
      },
    ];
  }
}
